import type { BetterSQLite3Database } from 'drizzle-orm/better-sqlite3';
import type { LibSQLDatabase } from 'drizzle-orm/libsql';
import { eq } from 'drizzle-orm';
import { companiesTable } from '@/db/schema';
import { logger } from '@/utils/logger';

interface CompanySeed {
  nameEn: string;
  nameAr: string | null;
  listId: 'companies' | 'saudi';
}

const companies: CompanySeed[] = [
  // Global companies
  { nameEn: 'x.com', nameAr: 'اكس', listId: 'companies' },
  { nameEn: 'Apple', nameAr: 'آبل', listId: 'companies' },
  { nameEn: 'Google', nameAr: 'جوجل', listId: 'companies' },
  { nameEn: 'Microsoft', nameAr: 'مايكروسوفت', listId: 'companies' },
  { nameEn: 'Amazon', nameAr: 'أمازون', listId: 'companies' },
  { nameEn: 'Meta Platforms', nameAr: 'ميتا', listId: 'companies' },
  { nameEn: 'Tesla', nameAr: 'تيسلا', listId: 'companies' },
  { nameEn: 'Netflix', nameAr: 'نتفليكس', listId: 'companies' },
  { nameEn: 'Spotify', nameAr: 'سبوتيفاي', listId: 'companies' },
  { nameEn: 'Nike', nameAr: 'نايكي', listId: 'companies' },
  { nameEn: 'Adidas', nameAr: 'أديداس', listId: 'companies' },
  { nameEn: 'Coca-Cola', nameAr: 'كوكا كولا', listId: 'companies' },
  { nameEn: 'wpbpepsi.com', nameAr: 'بيبسي', listId: 'companies' },
  { nameEn: 'McDonald\'s', nameAr: 'ماكدونالدز', listId: 'companies' },
  { nameEn: 'Starbucks', nameAr: 'ستاربكس', listId: 'companies' },
  { nameEn: 'Disney', nameAr: 'ديزني', listId: 'companies' },
  { nameEn: 'Sony', nameAr: 'سوني', listId: 'companies' },
  { nameEn: 'Samsung', nameAr: 'سامسونج', listId: 'companies' },
  { nameEn: 'intel.com', nameAr: 'إنتل', listId: 'companies' },
  { nameEn: 'NVIDIA', nameAr: 'إنفيديا', listId: 'companies' },
  { nameEn: 'Oracle', nameAr: 'أوراكل', listId: 'companies' },
  { nameEn: 'Adobe', nameAr: 'أدوبي', listId: 'companies' },
  { nameEn: 'Volkswagen', nameAr: 'مجموعة فولكسفاغن', listId: 'companies' },
  { nameEn: 'Uber', nameAr: 'أوبر', listId: 'companies' },
  { nameEn: 'Airbnb', nameAr: 'إير بي إن بي', listId: 'companies' },
  { nameEn: 'LinkedIn', nameAr: 'لينكد إن', listId: 'companies' },
  { nameEn: 'TikTok', nameAr: 'تيك توك', listId: 'companies' },
  { nameEn: 'Snapchat', nameAr: 'سناب شات', listId: 'companies' },
  { nameEn: 'Pinterest', nameAr: 'بينترست', listId: 'companies' },
  { nameEn: 'Reddit', nameAr: 'ريديت', listId: 'companies' },
  { nameEn: 'Walmart', nameAr: 'وول مارت', listId: 'companies' },
  { nameEn: 'Target', nameAr: 'تارجت', listId: 'companies' },
  { nameEn: 'Best Buy', nameAr: 'بست باي', listId: 'companies' },
  { nameEn: 'Ford', nameAr: 'فورد', listId: 'companies' },
  { nameEn: 'Toyota', nameAr: 'تويوتا', listId: 'companies' },
  { nameEn: 'BMW', nameAr: 'بي إم دبليو', listId: 'companies' },
  { nameEn: 'Mercedes', nameAr: 'مرسيدس', listId: 'companies' },
  { nameEn: 'Honda', nameAr: 'هوندا', listId: 'companies' },
  { nameEn: 'FedEx', nameAr: 'فيديكس', listId: 'companies' },
  { nameEn: 'Visa', nameAr: 'فيزا', listId: 'companies' },
  { nameEn: 'Mastercard', nameAr: 'ماستركارد', listId: 'companies' },
  { nameEn: 'Carrefour', nameAr: 'كارفور', listId: 'companies' },
  { nameEn: 'PayPal', nameAr: 'باي بال', listId: 'companies' },
  { nameEn: 'Zoom', nameAr: 'زووم', listId: 'companies' },
  { nameEn: 'Slack', nameAr: 'سلاك', listId: 'companies' },
  { nameEn: 'Saudi Aramco', nameAr: 'أرامكو السعودية', listId: 'companies' },
  { nameEn: 'Tencent', nameAr: 'تينسنت', listId: 'companies' },
  { nameEn: 'EA SPORTS', nameAr: 'إي إيه سبورتس', listId: 'companies' },
  { nameEn: 'Johnson & Johnson', nameAr: 'جونسون آند جونسون', listId: 'companies' },
  { nameEn: 'Alibaba', nameAr: 'علي بابا', listId: 'companies' },
  { nameEn: 'Procter & Gamble', nameAr: 'بروكتر آند غامبل (P&G)', listId: 'companies' },
  { nameEn: 'Hyundai', nameAr: 'هيونداي', listId: 'companies' },
  { nameEn: 'Louis Vuitton', nameAr: 'لويس فيتون', listId: 'companies' },
  { nameEn: 'Dior', nameAr: 'ديور', listId: 'companies' },
  { nameEn: 'General Electric', nameAr: 'جنرال إلكتريك', listId: 'companies' },
  { nameEn: 'Cisco', nameAr: 'سيسكو', listId: 'companies' },
  { nameEn: 'hermes.com', nameAr: 'هيرميس', listId: 'companies' },
  { nameEn: 'Nestlé', nameAr: 'نستله', listId: 'companies' },
  { nameEn: 'Mitsubishi', nameAr: 'ميتسوبيشي', listId: 'companies' },
  { nameEn: 'HSBC', nameAr: 'إتش إس بي سي', listId: 'companies' },
  { nameEn: 'loreal.com', nameAr: 'لوريال', listId: 'companies' },
  { nameEn: 'American Express', nameAr: 'أمريكان إكسبريس', listId: 'companies' },
  { nameEn: 'Shell', nameAr: 'شل', listId: 'companies' },
  { nameEn: 'Shopify', nameAr: 'شوبفاي', listId: 'companies' },
  { nameEn: 'IBM', nameAr: 'آي بي إم', listId: 'companies' },
  { nameEn: 'Dell', nameAr: 'ديل', listId: 'companies' },
  { nameEn: 'HP', nameAr: 'إتش بي', listId: 'companies' },
  { nameEn: 'Lenovo', nameAr: 'لينوفو', listId: 'companies' },
  { nameEn: 'ASUS', nameAr: 'أسوس', listId: 'companies' },
  { nameEn: 'Acer', nameAr: 'أيسر', listId: 'companies' },
  { nameEn: 'AMD', nameAr: 'إيه إم دي', listId: 'companies' },
  { nameEn: 'OpenAI', nameAr: 'أوبن أي آي', listId: 'companies' },
  { nameEn: 'Huawei', nameAr: 'هواوي', listId: 'companies' },
  { nameEn: 'oppo.com', nameAr: 'أوبو', listId: 'companies' },
  { nameEn: 'Xiaomi', nameAr: 'شاومي', listId: 'companies' },
  { nameEn: 'OnePlus', nameAr: 'ون بلس', listId: 'companies' },
  { nameEn: 'LG', nameAr: 'إل جي', listId: 'companies' },
  { nameEn: 'PlayStation', nameAr: 'بلايستيشن', listId: 'companies' },
  { nameEn: 'Nintendo', nameAr: 'نينتندو', listId: 'companies' },
  { nameEn: 'eBay', nameAr: 'إي باي', listId: 'companies' },
  { nameEn: 'Booking.com', nameAr: 'بوكينغ', listId: 'companies' },
  { nameEn: 'porsche.com', nameAr: 'بورش', listId: 'companies' },
  { nameEn: 'Ferrari', nameAr: 'فيراري', listId: 'companies' },
  { nameEn: 'Lamborghini', nameAr: 'لامبورغيني', listId: 'companies' },
  { nameEn: 'audi.com', nameAr: 'أودي', listId: 'companies' },
  { nameEn: 'Chevrolet', nameAr: 'شيفروليه', listId: 'companies' },
  { nameEn: 'Jeep', nameAr: 'جيب', listId: 'companies' },
  { nameEn: 'Nissan', nameAr: 'نيسان', listId: 'companies' },
  { nameEn: 'Kia', nameAr: 'كيا', listId: 'companies' },
  { nameEn: 'BP', nameAr: 'بي بي', listId: 'companies' },
  { nameEn: '3m.com', nameAr: 'ثري إم', listId: 'companies' },
  { nameEn: 'UPS', nameAr: 'يو بي إس', listId: 'companies' },
  { nameEn: 'DHL', nameAr: 'دي إتش إل', listId: 'companies' },
  { nameEn: 'shopcaterpillar.cl', nameAr: 'كاتربيلر', listId: 'companies' },
  { nameEn: 'Unilever', nameAr: 'يونيليفر', listId: 'companies' },
  { nameEn: 'IKEA', nameAr: 'إيكيا', listId: 'companies' },
  { nameEn: 'H&M', nameAr: 'إتش آند إم', listId: 'companies' },
  { nameEn: 'Zara', nameAr: 'زارا', listId: 'companies' },
  { nameEn: 'Gucci', nameAr: 'غوتشي', listId: 'companies' },
  { nameEn: 'Prada', nameAr: 'برادا', listId: 'companies' },
  { nameEn: 'Chanel', nameAr: 'شانيل', listId: 'companies' },
  { nameEn: 'Burberry', nameAr: 'بربري', listId: 'companies' },
  { nameEn: 'Lacoste', nameAr: 'لاكوست', listId: 'companies' },
  { nameEn: 'levi.com', nameAr: 'ليفايس', listId: 'companies' },
  { nameEn: 'Ralph Lauren', nameAr: 'رالف لورين', listId: 'companies' },
  { nameEn: 'KFC', nameAr: 'كنتاكي', listId: 'companies' },
  { nameEn: 'Burger King', nameAr: 'برجر كينغ', listId: 'companies' },
  { nameEn: 'Subway', nameAr: 'صب واي', listId: 'companies' },
  { nameEn: 'Domino\'s Pizza', nameAr: 'دومينوز بيتزا', listId: 'companies' },
  { nameEn: 'Papa John\'s', nameAr: 'بابا جونز', listId: 'companies' },
  { nameEn: 'Warner Bros.', nameAr: 'وارنر بروس', listId: 'companies' },
  { nameEn: 'Paramount', nameAr: 'باراماونت', listId: 'companies' },
  { nameEn: 'Universal', nameAr: 'يونيفرسال', listId: 'companies' },
  { nameEn: 'YouTube', nameAr: 'يوتيوب', listId: 'companies' },
  { nameEn: 'Twitch', nameAr: 'تويتش', listId: 'companies' },
  { nameEn: 'Epic Games', nameAr: 'إيبك غيمز', listId: 'companies' },
  { nameEn: 'Activision Blizzard', nameAr: 'أكتيفيجن بليزارد', listId: 'companies' },
  { nameEn: 'Roblox', nameAr: 'روبلكس', listId: 'companies' },
  { nameEn: 'STC', nameAr: 'إس تي سي', listId: 'companies' },

  // Saudi companies
  { nameEn: 'Aramco', nameAr: 'أرامكو', listId: 'saudi' },
  { nameEn: 'Alrajhi Bank', nameAr: 'مصرف الراجحي', listId: 'saudi' },
  { nameEn: 'Almarai', nameAr: 'المراعي', listId: 'saudi' },
  { nameEn: 'Riyad Bank', nameAr: 'بنك الرياض', listId: 'saudi' },
  { nameEn: 'Alinma Bank', nameAr: 'مصرف الإنماء', listId: 'saudi' },
  { nameEn: 'Dr Sulaiman AlHabib Medical Centers', nameAr: 'مجموعة الدكتور سليمان الحبيب الطبية', listId: 'saudi' },
  { nameEn: 'Mobily', nameAr: 'موبايلي', listId: 'saudi' },
  { nameEn: 'Elm Company', nameAr: 'شركة علم', listId: 'saudi' },
  { nameEn: 'Aldrees Petroleum', nameAr: 'الدريس للخدمات البترولية', listId: 'saudi' },
  { nameEn: 'stc.com.sa', nameAr: 'اس تي سي', listId: 'saudi' },
  { nameEn: 'SABIC', nameAr: 'سابك', listId: 'saudi' },
  { nameEn: 'alahli.com', nameAr: 'البنك الأهلي', listId: 'saudi' },
  { nameEn: 'Saudia', nameAr: 'الخطوط السعودية', listId: 'saudi' },
  { nameEn: 'Aljazira', nameAr: 'بنك الجزيرة', listId: 'saudi' },
  { nameEn: 'Nahdi Medical Co', nameAr: 'شركة النهدي الطبية', listId: 'saudi' },
  { nameEn: 'noon', nameAr: 'نون', listId: 'saudi' },
  { nameEn: 'jahez.net', nameAr: 'جاهز', listId: 'saudi' },
  { nameEn: 'HungerStation', nameAr: 'هنقرستيشن', listId: 'saudi' },
  { nameEn: 'nana.sa', nameAr: 'نعناع', listId: 'saudi' },
  { nameEn: 'tamara.co', nameAr: 'تمارا', listId: 'saudi' },
  { nameEn: 'tabby.ai', nameAr: 'تابي', listId: 'saudi' },
  { nameEn: 'Othaim Markets', nameAr: 'أسواق العثيم', listId: 'saudi' },
  { nameEn: 'Nadec', nameAr: 'نادك', listId: 'saudi' },
  { nameEn: 'Careem', nameAr: 'كريم', listId: 'saudi' },
  { nameEn: 'MBC GROUP', nameAr: 'مجموعة ام بي سي', listId: 'saudi' },
  { nameEn: 'Shahid', nameAr: 'شاهد', listId: 'saudi' },
  { nameEn: 'alarabiya', nameAr: 'العربية', listId: 'saudi' },
  { nameEn: 'sdaia.gov.sa', nameAr: 'سدايا', listId: 'saudi' },
  { nameEn: 'humain.ai', nameAr: 'هيوماين', listId: 'saudi' },
  { nameEn: 'zain.com', nameAr: 'زين', listId: 'saudi' },
  { nameEn: 'Jarir', nameAr: 'جرير', listId: 'saudi' },
  { nameEn: 'thmanyah', nameAr: 'ثمانية', listId: 'saudi' },
  { nameEn: 'zamil', nameAr: 'الزامل', listId: 'saudi' },
  { nameEn: 'se.com.sa', nameAr: 'الشركة السعودية للكهرباء', listId: 'saudi' },
  { nameEn: 'tawuniya', nameAr: 'التعاونية', listId: 'saudi' },
  { nameEn: 'splonline.com.sa', nameAr: 'سبل', listId: 'saudi' },
  { nameEn: 'sab.com', nameAr: 'الأول', listId: 'saudi' },
  { nameEn: 'Kudu company for food and catering', nameAr: 'كودو', listId: 'saudi' },
  { nameEn: 'Albaik', nameAr: 'البيك', listId: 'saudi' },
  { nameEn: 'extra.com', nameAr: 'اكسترا', listId: 'saudi' },
  { nameEn: 'haraj', nameAr: 'حراج', listId: 'saudi' },
  { nameEn: 'syarah', nameAr: 'سيارة', listId: 'saudi' },
  { nameEn: 'Panda Retail Company', nameAr: 'بنده', listId: 'saudi' },
  { nameEn: 'mrsool', nameAr: 'مرسول', listId: 'saudi' },
  { nameEn: 'NICE ONE', nameAr: 'نايس ون', listId: 'saudi' },
  { nameEn: 'performancegrowthlab.com', nameAr: 'لوسد موتورز', listId: 'saudi' },
  { nameEn: 'Petromin Corporation', nameAr: 'بترومين', listId: 'saudi' },
  { nameEn: 'rotanagroup.net', nameAr: 'روتانا', listId: 'saudi' },
  { nameEn: 'Camel Step', nameAr: 'خطوة جمل', listId: 'saudi' },
  { nameEn: 'Abdul Samad Al Qurashi', nameAr: 'عبد الصمد القرشي', listId: 'saudi' },
  { nameEn: 'Al Hatab Bakery', nameAr: 'الحطب فودز', listId: 'saudi' },
  { nameEn: 'aawsat', nameAr: 'صحيفة الشرق الأوسط', listId: 'saudi' },
  { nameEn: 'roshn.sa', nameAr: 'مجموعة روشن', listId: 'saudi' },
  { nameEn: 'saco.sa', nameAr: 'ساكو', listId: 'saudi' },
  { nameEn: 'Al Majed Oud', nameAr: 'الماجد للعود', listId: 'saudi' },
  { nameEn: 'al-dawaa.com.sa', nameAr: 'صيدليات الدواء', listId: 'saudi' },
  { nameEn: 'Almunajem Foods Company', nameAr: 'المنجم للأغذية', listId: 'saudi' },
  { nameEn: 'Mouwasat', nameAr: 'المواساة للخدمات الطبية', listId: 'saudi' },
  { nameEn: 'Dar Al Arkan', nameAr: 'دار الأركان', listId: 'saudi' },
  { nameEn: 'Halwani Brothers', nameAr: 'حلواني إخوان', listId: 'saudi' },
  { nameEn: 'First Mills', nameAr: 'المطاحن الأولى', listId: 'saudi' },
  { nameEn: 'alaseel.com.sa', nameAr: 'الأصيل', listId: 'saudi' },
  { nameEn: 'muvi Cinemas', nameAr: 'موڤي سينما', listId: 'saudi' },
  { nameEn: 'Maestro Pizza', nameAr: 'مايسترو بيتزا', listId: 'saudi' },
  { nameEn: 'Half Million', nameAr: 'هاف مليون', listId: 'saudi' },
  { nameEn: 'neom.com', nameAr: 'نيوم', listId: 'saudi' },
  { nameEn: 'alhokair.com', nameAr: 'مجموعة فواز عبد العزيز الحكير', listId: 'saudi' },
  { nameEn: 'Alsaif Gallery', nameAr: 'السيف غاليري', listId: 'saudi' },
  { nameEn: 'Tamimi Markets', nameAr: 'أسواق التميمي', listId: 'saudi' },
  { nameEn: 'Deraah Trading Company', nameAr: 'شركة درعه التجارية', listId: 'saudi' },
  { nameEn: 'Riyadh Air', nameAr: 'طيران الرياض', listId: 'saudi' },
  { nameEn: 'floward', nameAr: 'فلاورد', listId: 'saudi' },
  { nameEn: 'Fitness Time', nameAr: 'وقت اللياقة', listId: 'saudi' },
  { nameEn: 'eyewa', nameAr: 'آيوا', listId: 'saudi' },
  { nameEn: 'Herfy Food', nameAr: 'هرفي', listId: 'saudi' },
  { nameEn: 'burgerizzr', nameAr: 'برغرايززر', listId: 'saudi' },
  { nameEn: 'Al Safi Danone', nameAr: 'الصافي دانون', listId: 'saudi' },
  { nameEn: 'Altazaj', nameAr: 'الطازج', listId: 'saudi' },
  { nameEn: 'saptco', nameAr: 'سابتكو - الشركة السعودية للنقل الجماعي', listId: 'saudi' },
];

export async function seedD1Companies(
  db: BetterSQLite3Database<any> | LibSQLDatabase<any>,
) {
  logger.info({ count: companies.length }, 'Seeding companies...');

  let seeded = 0;

  for (const company of companies) {
    const existing = await db
      .select()
      .from(companiesTable)
      .where(eq(companiesTable.nameEn, company.nameEn))
      .get();

    if (!existing) {
      await db.insert(companiesTable).values({
        nameEn: company.nameEn,
        nameAr: company.nameAr,
        listId: company.listId,
      });
      seeded++;
    }
  }

  logger.info({ seeded, total: companies.length }, 'Companies seeded successfully!');
}
