export function generateCompanyLogoUrl(name: string) {
  const query = name.toLowerCase().replace(/[^a-z0-9]/g, '');
  return `https://api.logo.dev/search?q=${query}`;
}

export function generateMoviePosterUrl(name: string) {
  const query = encodeURIComponent(name);
  // First try Arabic, fallback to English if needed
  return `https://api.themoviedb.org/3/search/movie?include_adult=false&language=ar&page=1&query=${query}`;
}

const companyNames = [
  'Apple',
  'Google',
  'Microsoft',
  'Amazon',
  'Meta',
  'Tesla',
  'Netflix',
  'Spotify',
  'Nike',
  'Adidas',
  'Coca-Cola',
  'Pepsi',
  'McDonald\'s',
  'Starbucks',
  'Disney',
  'Sony',
  'Samsung',
  'Intel',
  'AMD',
  'NVIDIA',
  'IBM',
  'Oracle',
  'Salesforce',
  'Adobe',
  'Uber',
  'Airbnb',
  'Twitter',
  'LinkedIn',
  'TikTok',
  'Snapchat',
  'Pinterest',
  'Reddit',
  'Walmart',
  'Target',
  'Best Buy',
  'Home Depot',
  'Ford',
  'Toyota',
  'BMW',
  'Mercedes',
  'Visa',
  'Mastercard',
  'PayPal',
  'Square',
  'Stripe',
  'Zoom',
  'Slack',
  'Dropbox',
];

const countryNames = [
  'United States',
  'Canada',
  'Mexico',
  'Brazil',
  'Argentina',
  'United Kingdom',
  'France',
  'Germany',
  'Italy',
  'Spain',
  'Russia',
  'China',
  'Japan',
  'South Korea',
  'India',
  'Australia',
  'Egypt',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Turkey',
  'Greece',
  'Netherlands',
  'Belgium',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Poland',
  'Czech Republic',
  'Hungary',
  'Romania',
  'Portugal',
  'Switzerland',
  'Austria',
  'Ireland',
  'Israel',
  'Saudi Arabia',
  'UAE',
  'Iran',
  'Thailand',
  'Vietnam',
  'Philippines',
  'Indonesia',
  'Malaysia',
  'Singapore',
  'New Zealand',
  'Chile',
];

const movieNames = [
  'Avatar',
  'Titanic',
  'Star Wars',
  'Avengers',
  'Jurassic Park',
  'The Lion King',
  'Frozen',
  'Incredibles',
  'Finding Nemo',
  'Shrek',
  'Toy Story',
  'Cars',
  'Up',
  'WALL-E',
  'Monsters Inc',
  'Coco',
  'Moana',
  'Zootopia',
  'Big Hero 6',
  'Wreck-It Ralph',
  'Tangled',
  'Brave',
  'Inside Out',
  'Soul',
  'Luca',
  'Turning Red',
  'Encanto',
  'Raya',
  'Onward',
  'The Good Dinosaur',
  'A Bug\'s Life',
  'Ratatouille',
  'Harry Potter',
  'Lord of the Rings',
  'The Matrix',
  'Batman',
  'Superman',
  'Spider-Man',
  'Iron Man',
  'Thor',
  'Captain America',
  'Black Panther',
  'Wonder Woman',
  'Aquaman',
  'The Flash',
  'Green Lantern',
  'Deadpool',
  'X-Men',
];
export const sportsNames = [
  // English Premier League
  { name: 'Manchester United', id: 33 },
  { name: 'Liverpool', id: 34 },
  { name: 'Manchester City', id: 50 },
  { name: 'Chelsea', id: 49 },
  { name: 'Arsenal', id: 42 },
  { name: 'Tottenham Hotspur', id: 47 },
  { name: 'Leicester City', id: 15394 },
  { name: 'Everton', id: 45 },

  // European
  { name: 'Real Madrid', id: 541 },
  { name: 'Barcelona', id: 529 },
  { name: 'Bayern Munich', id: 157 },
  { name: 'Juventus', id: 496 },
  { name: 'Paris Saint-Germain', id: 85 },
  { name: 'AC Milan', id: 489 },
  { name: 'Inter Milan', id: 505 },
  { name: 'Borussia Dortmund', id: 165 },
  { name: 'Atletico Madrid', id: 530 },
  { name: 'Ajax', id: 181 },
  { name: 'Benfica', id: 212 },
  { name: 'Porto', id: 206 },

  // Saudi Pro League
  { name: 'Al-Hilal', id: 2932 },
  { name: 'Al-Nassr', id: 2935 },
  { name: 'Al-Ittihad', id: 2931 },
  { name: 'Al-Ahli', id: 2933 },
  { name: 'Al-Shabab', id: 2934 },
  { name: 'Al-Faisaly', id: 2936 },
  { name: 'Al-Taawoun', id: 2937 },
  { name: 'Al-Raed', id: 2938 },
  { name: 'Al-Ettifaq', id: 2940 },
  { name: 'Abha', id: 2942 },
];

export const logoSets = {
  companies: companyNames,
  countries: countryNames,
  movies: movieNames,
  sports: sportsNames,
};

export type LogoSetKey = keyof typeof logoSets;
export type SportsLogoItem = typeof sportsNames[number];
