export function generateCompanyLogoUrl(name: string) {
  const query = name.toLowerCase().replace(/[^a-z0-9]/g, '')
  return `https://api.logo.dev/search?q=${query}`
}

export function generateMoviePosterUrl(name: string) {
  const query = encodeURIComponent(name)
  // First try Arabic, fallback to English if needed
  return `https://api.themoviedb.org/3/search/movie?include_adult=false&language=ar&page=1&query=${query}`
}

const companyNames = [
  'Apple',
  'Google',
  'Microsoft',
  'Amazon',
  'Meta',
  'Tesla',
  'Netflix',
  'Spotify',
  'Nike',
  'Adidas',
  'Coca-Cola',
  'Pepsi',
  'McDonald\'s',
  'Starbucks',
  'Disney',
  'Sony',
  'Samsung',
  'Intel',
  'AMD',
  'NVIDIA',
  'IBM',
  'Oracle',
  'Salesforce',
  'Adobe',
  'Uber',
  'Airbnb',
  'Twitter',
  'LinkedIn',
  'TikTok',
  'Snapchat',
  'Pinterest',
  'Reddit',
  'Walmart',
  'Target',
  'Best Buy',
  'Home Depot',
  'Ford',
  'Toyota',
  'BMW',
  'Mercedes',
  'Visa',
  'Mastercard',
  'PayPal',
  'Square',
  'Stripe',
  'Zoom',
  'Slack',
  'Dropbox',
]

const countryNames = [
  'United States',
  'Canada',
  'Mexico',
  'Brazil',
  'Argentina',
  'United Kingdom',
  'France',
  'Germany',
  'Italy',
  'Spain',
  'Russia',
  'China',
  'Japan',
  'South Korea',
  'India',
  'Australia',
  'Egypt',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Turkey',
  'Greece',
  'Netherlands',
  'Belgium',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Poland',
  'Czech Republic',
  'Hungary',
  'Romania',
  'Portugal',
  'Switzerland',
  'Austria',
  'Ireland',
  'Israel',
  'Saudi Arabia',
  'UAE',
  'Iran',
  'Thailand',
  'Vietnam',
  'Philippines',
  'Indonesia',
  'Malaysia',
  'Singapore',
  'New Zealand',
  'Chile',
]

const movieNames = [
  'Avatar',
  'Titanic',
  'Star Wars',
  'Avengers',
  'Jurassic Park',
  'The Lion King',
  'Frozen',
  'Incredibles',
  'Finding Nemo',
  'Shrek',
  'Toy Story',
  'Cars',
  'Up',
  'WALL-E',
  'Monsters Inc',
  'Coco',
  'Moana',
  'Zootopia',
  'Big Hero 6',
  'Wreck-It Ralph',
  'Tangled',
  'Brave',
  'Inside Out',
  'Soul',
  'Luca',
  'Turning Red',
  'Encanto',
  'Raya',
  'Onward',
  'The Good Dinosaur',
  'A Bug\'s Life',
  'Ratatouille',
  'Harry Potter',
  'Lord of the Rings',
  'The Matrix',
  'Batman',
  'Superman',
  'Spider-Man',
  'Iron Man',
  'Thor',
  'Captain America',
  'Black Panther',
  'Wonder Woman',
  'Aquaman',
  'The Flash',
  'Green Lantern',
  'Deadpool',
  'X-Men',
]

const sportsNames = [
  'FIFA',
  'NBA',
  'NFL',
  'MLB',
  'NHL',
  'UEFA',
  'Olympics',
  'Premier League',
  'La Liga',
  'Serie A',
  'Bundesliga',
  'Ligue 1',
  'Champions League',
  'World Cup',
  'Super Bowl',
  'Stanley Cup',
  'Wimbledon',
  'US Open',
  'French Open',
  'Australian Open',
  'Masters',
  'PGA',
  'Formula 1',
  'NASCAR',
  'MLS',
  'EPL',
  'Juventus',
  'Barcelona',
  'Real Madrid',
  'Manchester United',
  'Liverpool',
  'Arsenal',
  'Chelsea',
  'Manchester City',
  'PSG',
  'Bayern Munich',
  'AC Milan',
  'Inter Milan',
  'Atletico Madrid',
  'Borussia Dortmund',
  'Ajax',
  'Porto',
  'Benfica',
  'Celtic',
  'Rangers',
  'Galatasaray',
  'Fenerbahce',
  'Olympiacos',
]

export const logoSets = {
  companies: companyNames,
  countries: countryNames,
  movies: movieNames,
  sports: sportsNames,
}

export interface LogoItem {
  id: number
  name: string
  imageUrl: string
  eliminated: boolean
}

export type LogoSetKey = keyof typeof logoSets
