/* eslint-disable no-console */
import path from 'node:path';
import process from 'node:process';
import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import { afterAll, beforeAll, vi } from 'vitest';

// eslint-disable-next-line import/no-mutable-exports
export let db: ReturnType<typeof drizzle>;

vi.mock('cloudflare:workers', () => ({}));
vi.mock('cloudflare:test', () => ({}));

(globalThis as any).caches = {
  default: { async match() { return null; }, async put() {} },
};
(globalThis as any).env = {
  SESSION_KV: { async get() { return null; }, async put() {}, async delete() {} },
};

process.on('uncaughtException', e => console.error('❌ Uncaught exception:', e));
process.on('unhandledRejection', e => console.error('❌ Unhandled rejection:', e));

beforeAll(async () => {
  // ✅ Create a temporary in-memory DB (fastest for tests)
  const sqlite = new Database(':memory:');

  // Or use file if you want persistence across tests:
  // const sqlite = new Database(path.resolve(__dirname, '../.test.db'));

  db = drizzle(sqlite);

  // ✅ Run migrations (generated by drizzle-kit)
  await migrate(db, { migrationsFolder: path.resolve('./drizzle') });

  console.log('🧪 Using in-memory better-sqlite3 database for Vitest');
});

afterAll(async () => {
  // Close DB cleanly
  (db as any)?.session?.close?.();
  console.log('🧹 Closed in-memory test database');
});
