// biome-ignore-all format: generated
// This file is auto-generated by kitcn
// Do not edit manually. Run `kitcn codegen` to regenerate.

import { createApiLeaf, createGeneratedFunctionReference } from "kitcn/server";
import type { inferApiInputs, inferApiOutputs } from "kitcn/server";


export const api = {
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

