// packages/shared/scripts/region-map.ts
export const REGION_MAP: Record<string, string> = {
  // 🌍 Africa
  'algeria': 'africa',
  'angola': 'africa',
  'benin': 'africa',
  'botswana': 'africa',
  'burkina-faso': 'africa',
  'burundi': 'africa',
  'cameroon': 'africa',
  'congo': 'africa',
  'congo-dr': 'africa',
  'egypt': 'africa',
  'ethiopia': 'africa',
  'gabon': 'africa',
  'gambia': 'africa',
  'ghana': 'africa',
  'ivory-coast': 'africa',
  'kenya': 'africa',
  'lesotho': 'africa',
  'libya': 'africa',
  'morocco': 'africa',
  'nigeria': 'africa',
  'senegal': 'africa',
  'south-africa': 'africa',
  'sudan': 'africa',
  'tanzania': 'africa',
  'tunisia': 'africa',
  'uganda': 'africa',
  'zambia': 'africa',
  'zimbabwe': 'africa',

  // 🇪🇺 Europe
  'england': 'europe',
  'france': 'europe',
  'germany': 'europe',
  'italy': 'europe',
  'spain': 'europe',
  'portugal': 'europe',
  'netherlands': 'europe',
  'belgium': 'europe',
  'poland': 'europe',
  'sweden': 'europe',
  'norway': 'europe',
  'switzerland': 'europe',
  'denmark': 'europe',
  'austria': 'europe',
  'croatia': 'europe',
  'serbia': 'europe',
  'greece': 'europe',
  'turkey': 'europe',
  'ukraine': 'europe',
  'russia': 'europe',

  // 🌏 Asia
  'Saudi-arabia': 'asia',
  'japan': 'asia',
  'china': 'asia',
  'india': 'asia',
  'iran': 'asia',
  'iraq': 'asia',
  'jordan': 'asia',
  'kuwait': 'asia',
  'lebanon': 'asia',
  'malaysia': 'asia',
  'qatar': 'asia',
  'singapore': 'asia',
  'south-korea': 'asia',
  'syria': 'asia',
  'thailand': 'asia',
  'uae': 'asia',
  'yemen': 'asia',

  // 🌎 North America
  'canada': 'north-america',
  'usa': 'north-america',
  'mexico': 'north-america',
  'jamaica': 'north-america',
  'trinidad-and-tobago': 'north-america',
  'haiti': 'north-america',
  'honduras': 'north-america',
  'panama': 'north-america',
  'belize': 'north-america',
  'cuba': 'north-america',
  'guatemala': 'north-america',

  // 🌎 South America
  'argentina': 'south-america',
  'bolivia': 'south-america',
  'brazil': 'south-america',
  'chile': 'south-america',
  'colombia': 'south-america',
  'ecuador': 'south-america',
  'paraguay': 'south-america',
  'peru': 'south-america',
  'uruguay': 'south-america',
  'venezuela': 'south-america',

  // 🌊 Oceania
  'australia': 'oceania',
  'new-zealand': 'oceania',
  'fiji': 'oceania',
};
