name = "game-rooms-api"
main = "src/app.ts"
compatibility_date = "2025-09-01"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = true

[vars]
ALLOWED_ORIGINS = "http://localhost:5173,http://localhost:4173,https://guess-logo.pages.dev,https://games.mohdalaa.com"
API_URL = "http://localhost:8787"

[[durable_objects.bindings]]
name = "GAME_SESSION"
class_name = "GameSessionObject"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_sqlite_classes = [ "GameSessionObject" ]

# Array of new classes
[observability]
enabled = true

# KV namespaces for caching and rate limiting
[[kv_namespaces]]
binding = "LOGO_CACHE"
id = "eb1698afccf64de8993284056aaa5598"
preview_id = "beac11884fff4280a9ecad02adf2961c"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "2935fac12f184133b095fc52a402d801"
preview_id = "57a9aedd01974845a191abf28f2b2710"

[[kv_namespaces]]
binding = "QUESTIONS"
id = "07bd0d479a8444139fc0b3584f9c28ae"
preview_id = "07bd0d479a8444139fc0b3584f9c28ae"

[[d1_databases]]
binding = "GAME_HUB_DB"
database_name = "GAME_HUB_DB"
database_id = "985b789d-4062-4f3f-9abb-0b9553650548"
migrations_dir = "drizzle"
