name = "game-rooms-api"
main = "src/app.ts"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "public"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoomDurableObject"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_sqlite_classes = [ "GameRoomDurableObject" ]

# Array of new classes
[observability]
enabled = true

# KV namespaces for caching and rate limiting
[[kv_namespaces]]
binding = "LOGO_CACHE"
id = "eb1698afccf64de8993284056aaa5598"
preview_id = "beac11884fff4280a9ecad02adf2961c"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "2935fac12f184133b095fc52a402d801"
preview_id = "57a9aedd01974845a191abf28f2b2710"
